### ISSUE TITLE
the version in Bot::ChatBots::MojoPlugin pod isn't shown

### ISSUE THREAD

**Issue by wchristian** [polettix/Bot-ChatBots#2]
See: https://metacpan.org/pod/Bot::ChatBots::MojoPlugin#VERSION

**Comment by polettix** [comment]
Well spotted, I forgot to remove it (I usually keep the version in the main module only)

**Comment by polettix** [comment]
Fixed in https://github.com/polettix/Bot-ChatBots/commit/72d11b7c716c1df685e6a084914c82a0a0e6958b.
